version: '3.7'
services:
  characters_microservice:
    restart: always
    build: .
    image: characters_microservice:characters
    ports:
      - "8082:8082"
    command: flask run --host=0.0.0.0 --port 8082
    depends_on:
      - postgresql
  data:
    image: postgresql:9.6
    volumes:
      - /var/lib/postgresql
    command: "true"
  postgresql:
    restart: always
    build: ./postgresql
    volumes:
      - data
    expose:
      - "5432"



