version: '3.7'
services:
  characters_microservice:
    restart: always
    build: .
    ports:
      - "8081:8081"
    volumes:
      - /home/flask/app/characters_microservice
    command: flask run --host=0.0.0.0 --port 8081
  postgres_characters:
    restart: always
    build: ./postgresql
    volumes:
      - /var/lib/postgresql_characters
    expose:
      - "5432"
